// Copyright (c) 2025 МультиКод Team. MIT License.

#include "visprog/generators/CppCodeGenerator.hpp"

#include <sstream>

namespace visprog::generators {

auto CppCodeGenerator::generate(const core::Graph& graph) -> core::Result<std::string> {
    // Basic implementation for now. This will be expanded.
    std::stringstream ss;
    ss << "// Generated by MultiCode C++ Code Generator\n";
    ss << "#include <iostream>\n\n";
    ss << "int main() {\n";
    ss << "    std::cout << \"Hello from generated code!\\n\";\n";
    ss << "    return 0;\n";
    ss << "}\n";

    return core::Result<std::string>{ss.str()};
}

}  // namespace visprog::generators
